# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e8d34410680b54775013dfbb65cfc89272aa0f1a84ce6f3facc86f4b6849deec75766c83171ef640ce631c4c793079bd2fa7dc4241aa6f268264c1af7c69379a

test:
  secret_key_base: 27c938bb98f5b5701e9ee3571e3028430b121cc742af4e64b42f6b26c21ba92f284d8ce20c01206d1e763b9a4928155d6139558a08b61893953fdbe4c4264286

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
